
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sklad.Classes
{

using System;
    using System.Collections.Generic;
    
public partial class Application
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Application()
    {

        this.Purchase = new HashSet<Purchase>();

    }


    public int IDapplication { get; set; }

    public string DateApplication { get; set; }

    public Nullable<int> IDpharmacy { get; set; }

    public string DateCompletion { get; set; }



    public virtual Phaemacy Phaemacy { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Purchase> Purchase { get; set; }

}

}
