
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sklad.Classes
{

using System;
    using System.Collections.Generic;
    
public partial class Medicament
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Medicament()
    {

        this.Purchase = new HashSet<Purchase>();

        this.Basket = new HashSet<Basket>();

    }


    public int IDmedicament { get; set; }

    public string NazvanieMedicament { get; set; }

    public int Price { get; set; }

    public Nullable<int> IDmanufacturer { get; set; }

    public Nullable<int> IDtype { get; set; }

    public string Image { get; set; }



    public virtual Manufacturer Manufacturer { get; set; }

    public virtual Type Type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Purchase> Purchase { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Basket> Basket { get; set; }

}

}
