
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace sklad.Classes
{

using System;
    using System.Collections.Generic;
    
public partial class Purchase
{

    public int IDpurchase { get; set; }

    public Nullable<int> IDapplication { get; set; }

    public Nullable<int> IDmedicament { get; set; }

    public int Quantity { get; set; }



    public virtual Application Application { get; set; }

    public virtual Medicament Medicament { get; set; }

}

}
